export { APIProvider, useAPI } from './APIcontext'
export { NotesProvider, useNotes, generateIcon } from './Notes'
export { PerfilProvider, usePerfil } from './Perfil'
export { ThemeProvider, useTheme } from './Theme'
export { DocProvider, useDoc } from './DocContext'
export { NavigateProvider, useNavigate } from './Navigate'